### ISSUE TITLE
/coord command crashing game with some coordinates

### ISSUE THREAD

**Issue by johnysandels** [kissorjeyabalan/dalamud-chatcoordinates#4]
Some chat coordinates are creating malformed flags which crash the game. One flag that consistently crashes the game is `/coord 26.7 27.5 :Amh Araeng` It crashes no matter the formatting of the command.

`/coord 20.0 20.0 :Central Shroud` also causes a crash for some people. on my device this second command crashed my game once, and didn't crash after that.

**Comment by johnysandels** [comment]
Any idea what would cause the malformed flag?

**Comment by kissorjeyabalan** [comment]
Unable to reproduce issue. 

I've fixed the issue caused by ChatCoordinates that you reported here: Ottermandias/GatherBuddy#4.
It is possible that the malformed link had something to do with the issue.

I'll publish the fix after Dalamud API level 3 is released.

**Comment by johnysandels** [comment]
Amazing!

**Comment by johnysandels** [comment]
Just compiled and it works great. thank you for looking into it!
