### ISSUE TITLE
Error message after latest Dalamud update

### ISSUE THREAD

**Issue by MarkusWo** [kissorjeyabalan/dalamud-chatcoordinates#8]
With the new Dalamud 6.0.0.0 update I am getting an error message whenever I use the /ctp command. "Teleporting requires Teleporter plugin to be installed.". The teleporter plugin is installed though and reacts correctly to its /tp and /tpm commands. So I am not sure why it wouldn't work but maybe something needs to be done on the chatcoordinate side of things? thank you in advance

**Comment by z-Kana** [comment]
i have the same problem, have u fixed or found a solution to it?

**Comment by MarkusWo** [comment]
Unfortunately no. I can just say that Teleporter plugin and every other plugin that has some teleporting function work perfectly. It is only chatcoordinates that doesn't.

**Comment by wiiaboo** [comment]
Teleporter plugin removed `/tpt` with the rework for the new API, there's only `/tp` and `/tpm`.
